# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /opt/unreal-engine

TARGETS = \
	ActionRoguelike-Android-DebugGame  \
	ActionRoguelike-Android-Development  \
	ActionRoguelike-Android-Shipping  \
	ActionRoguelike-Linux-DebugGame  \
	ActionRoguelike-Linux-Development  \
	ActionRoguelike-Linux-Shipping  \
	ActionRoguelike-LinuxArm64-DebugGame  \
	ActionRoguelike-LinuxArm64-Development  \
	ActionRoguelike-LinuxArm64-Shipping  \
	ActionRoguelike \
	ActionRoguelikeEditor-Linux-DebugGame  \
	ActionRoguelikeEditor-Linux-Development  \
	ActionRoguelikeEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend ActionRoguelikeEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug ActionRoguelikeEditor-Linux-Debug


ActionRoguelike-Android-DebugGame:
	 $(BUILD) ActionRoguelike Android DebugGame  -Project="/home/lync/Projects/ActionRoguelike/ActionRoguelike.uproject" $(ARGS)

ActionRoguelike-Android-Development:
	 $(BUILD) ActionRoguelike Android Development  -Project="/home/lync/Projects/ActionRoguelike/ActionRoguelike.uproject" $(ARGS)

ActionRoguelike-Android-Shipping:
	 $(BUILD) ActionRoguelike Android Shipping  -Project="/home/lync/Projects/ActionRoguelike/ActionRoguelike.uproject" $(ARGS)

ActionRoguelike-Linux-DebugGame:
	 $(BUILD) ActionRoguelike Linux DebugGame  -Project="/home/lync/Projects/ActionRoguelike/ActionRoguelike.uproject" $(ARGS)

ActionRoguelike-Linux-Development:
	 $(BUILD) ActionRoguelike Linux Development  -Project="/home/lync/Projects/ActionRoguelike/ActionRoguelike.uproject" $(ARGS)

ActionRoguelike-Linux-Shipping:
	 $(BUILD) ActionRoguelike Linux Shipping  -Project="/home/lync/Projects/ActionRoguelike/ActionRoguelike.uproject" $(ARGS)

ActionRoguelike-LinuxArm64-DebugGame:
	 $(BUILD) ActionRoguelike LinuxArm64 DebugGame  -Project="/home/lync/Projects/ActionRoguelike/ActionRoguelike.uproject" $(ARGS)

ActionRoguelike-LinuxArm64-Development:
	 $(BUILD) ActionRoguelike LinuxArm64 Development  -Project="/home/lync/Projects/ActionRoguelike/ActionRoguelike.uproject" $(ARGS)

ActionRoguelike-LinuxArm64-Shipping:
	 $(BUILD) ActionRoguelike LinuxArm64 Shipping  -Project="/home/lync/Projects/ActionRoguelike/ActionRoguelike.uproject" $(ARGS)

ActionRoguelike: ActionRoguelike-Linux-Development

ActionRoguelikeEditor-Linux-DebugGame:
	 $(BUILD) ActionRoguelikeEditor Linux DebugGame  -Project="/home/lync/Projects/ActionRoguelike/ActionRoguelike.uproject" $(ARGS)

ActionRoguelikeEditor-Linux-Development:
	 $(BUILD) ActionRoguelikeEditor Linux Development  -Project="/home/lync/Projects/ActionRoguelike/ActionRoguelike.uproject" $(ARGS)

ActionRoguelikeEditor: ActionRoguelikeEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/lync/Projects/ActionRoguelike/ActionRoguelike.uproject" -Game 

.PHONY: $(TARGETS)
